databases:
  - name: django_render_db
    region: singapore
    plan: free
    databaseName: django_render_db
    user: django_user

services:
  - type: web
    name: University_Naniritsu_Judge_Kun
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn django-website-08-master.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_render_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true
