# Generated by Django 4.1.4 on 2023-02-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("text_edit", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Post",),
    ]
